name: Auto Reply to New Issues

on:
  issues:
    types: [opened]

jobs:
  auto-reply:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on the new issue
        uses: actions/github-script@v6
        with:
          script: |
            const { issue } = context.payload;
            const { owner, repo } = context.repo;
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);

            // Define your reply message
            const replyMessage = "Thank you for opening an issue! We will get back to you as soon as possible.";

            // Post a comment on the issue
            await octokit.rest.issues.createComment({
              owner,
              repo,
              issue_number: issue.number,
              body: replyMessage
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}